---
# INFO: convert existing keys to age:
# ssh-to-age -i ~/.ssh/id_ed25519.pub

# NOTE: sops updatekeys secrets/secrets.yaml if you add/remove any keys:
# sops updatekeys secrets/secrets.yaml
keys:
  - &blackout age1n5sdzcldm3s84vgxg3x2ru5esawkkn524zudz6gt37rh4xshmymsah7e7a
  - &energon age1g23fnmeanjp2jqu2kzgfghnt62uvcrz7axfe3sqm77a3z3xgxfus68y8yx
  - &galvatron age1smufwuynmlycgjda4c8erg4rqstdx9ds3020wakvpdre7j6x7ynqgw9n2f
  - &optimus age14kdp2039nk79aa8ytkc8p5acv2vrkd6dn8alj497q4k3u98kua6syzp0s5
  - &ratchet age1t32akwkq7tv4ac0y24xmjh6t4t08e6kqu2ztz9pgh64tqcgcecps24gmus

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *blackout
          - *energon
          - *galvatron
          - *optimus
          - *ratchet
