_:
let
  inherit (import ../variables.nix)
    browser
    terminal
    ;
in
{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$modifier,Return,exec,uwsm app -- ${terminal}"
      "$modifier SHIFT,Return,exec,rofi-launcher"
      #----------MOD---------------------------------------->>
      "$modifier,B,exec,uwsm app -- ${browser}"
      "$modifier,C,exec,hyprpicker -a"
      "$modifier,D,exec,uwsm app -- discord"
      "$modifier,E,exec,emopicker9000"
      "$modifier,F,fullscreen,"
      "$modifier,G,exec,uwsm app -- gimp"
      "$modifier,K,exec,list-keybinds"
      "$modifier,M,exec,uwsm app -- modrinth-app"
      "$modifier,O,exec,uwsm app -- obs"
      "$modifier,P,exec,uwsm app -- plex-desktop"
      "$modifier,Q,killactive,"
      "$modifier,S,exec,uwsm app -- signal-desktop"
      "$modifier,T,exec,uwsm app -- thunar"
      "$modifier,V,exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"
      "$modifier,Y,exec,uwsm app -- kitty -e yazi"
      #----------MOD-SHIFT---------------------------------->>
      "$modifier SHIFT,C,exit,"
      "$modifier SHIFT,D,exec,uwsm app -- davinci-resolve"
      "$modifier SHIFT,F,togglefloating,"
      "$modifier SHIFT,G,exec,uwsm app -- godot4"
      "$modifier SHIFT,I,togglesplit,"
      "$modifier SHIFT,M,exec,uwsm app -- mullvad-vpn"
      "$modifier SHIFT,N,exec,swaync-client -rs"
      "$modifier SHIFT,P,exec,uwsm app -- plexamp"
      "$modifier SHIFT,S,exec,screenshootin"
      "$modifier SHIFT,W,exec,web-search"
      "$modifier SHIFT,left,movewindow,l"
      "$modifier SHIFT,right,movewindow,r"
      "$modifier SHIFT,up,movewindow,u"
      "$modifier SHIFT,down,movewindow,d"
      "$modifier SHIFT,h,movewindow,l"
      "$modifier SHIFT,l,movewindow,r"
      "$modifier SHIFT,k,movewindow,u"
      "$modifier SHIFT,j,movewindow,d"
      #----------MOD-ALT------------------------------------>>
      "$modifier ALT,B,exec,bazecor"
      "$modifier ALT,D,exec,pseudo" # Dwindle
      "$modifier ALT,G,exec,gparted"
      "$modifier ALT,P,exec,pavucontrol"
      "$modifier ALT,F,workspaceopt, allfloat"
      "$modifier ALT, left, swapwindow,l"
      "$modifier ALT, right, swapwindow,r"
      "$modifier ALT, up, swapwindow,u"
      "$modifier ALT, down, swapwindow,d"
      "$modifier ALT, 43, swapwindow,l"
      "$modifier ALT, 46, swapwindow,r"
      "$modifier ALT, 45, swapwindow,u"
      "$modifier ALT, 44, swapwindow,d"
      #----------WORKSPACES--------------------------------->>
      "$modifier,left,movefocus,l"
      "$modifier,right,movefocus,r"
      "$modifier,up,movefocus,u"
      "$modifier,down,movefocus,d"
      "$modifier,h,movefocus,l"
      "$modifier,l,movefocus,r"
      "$modifier,k,movefocus,u"
      "$modifier,j,movefocus,d"
      "$modifier,1,workspace,1"
      "$modifier,2,workspace,2"
      "$modifier,3,workspace,3"
      "$modifier,4,workspace,4"
      "$modifier,5,workspace,5"
      "$modifier,6,workspace,6"
      "$modifier,7,workspace,7"
      "$modifier,8,workspace,8"
      "$modifier,9,workspace,9"
      "$modifier,0,workspace,10"
      "$modifier SHIFT,SPACE,movetoworkspace,special"
      "$modifier,SPACE,togglespecialworkspace"
      "$modifier SHIFT,1,movetoworkspace,1"
      "$modifier SHIFT,2,movetoworkspace,2"
      "$modifier SHIFT,3,movetoworkspace,3"
      "$modifier SHIFT,4,movetoworkspace,4"
      "$modifier SHIFT,5,movetoworkspace,5"
      "$modifier SHIFT,6,movetoworkspace,6"
      "$modifier SHIFT,7,movetoworkspace,7"
      "$modifier SHIFT,8,movetoworkspace,8"
      "$modifier SHIFT,9,movetoworkspace,9"
      "$modifier SHIFT,0,movetoworkspace,10"
      "$modifier CONTROL,right,workspace,e+1"
      "$modifier CONTROL,left,workspace,e-1"
      "$modifier,mouse_down,workspace, e+1"
      "$modifier,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      "ALT,space,exec,uwsm app -- albert show"
      #----------AUDIO----------------------------------->>
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "$modifier, mouse:272, movewindow"
      "$modifier, mouse:273, resizewindow"
    ];
  };
}
