_: {
  wayland.windowManager.hyprland = {
    settings = {
      windowrule = [
        "class:^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$, tag +file-manager"
        "class:^(com.mitchellh.ghostty|org.wezfurlong.wezterm|Alacritty|kitty|kitty-dropterm)$, tag +terminal"
        "class:^(Brave-browser(-beta|-dev|-unstable)?)$, tag +browser"
        "class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$, tag +browser"
        "class:^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$, tag +browser"
        "class:^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$, tag +im"
        "class:^(gamescope)$, tag +games"
        "class:^(steam_app_\\d+)$, tag +games"
        "class:^([Ss]team)$, tag +gamestore"
        "title:^([Ll]utris)$, tag +gamestore"
        "class:^(com.heroicgameslauncher.hgl)$, tag +gamestore"
        "class:^(gnome-disks|wihotspot(-gui)?)$, tag +settings"
        "class:^([Rr]ofi)$, tag +settings"
        "class:^(nm-applet|nm-connection-editor|blueman-manager)$, tag +settings"
        "class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$, tag +settings"
        "class:^(nwg-look|qt5ct|qt6ct|[Yy]ad)$, tag +settings"
        "class:(xdg-desktop-portal-gtk), tag +settings"
        "class:(.blueman-manager-wrapped), tag +settings"
        "class:(nwg-displays), tag +settings"
        "title:^(Picture-in-Picture)$, move 72% 7%"
        "class:^([Ff]erdium)$, center"
        "class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$, center"
        "class:([Tt]hunar), title:negative:(.*[Tt]hunar.*), center"
        "title:^(Authentication Required)$, center"
        "class:^.*$, idleinhibit fullscreen"
        "title:^.*$, idleinhibit fullscreen"
        "fullscreen:1, idleinhibit"
        "class:^(Steam_App_\\d+)$, focus"
        "tag:settings*, float"
        "class:^([Ff]erdium)$, float"
        "title:^(Picture-in-Picture)$, float"
        "class:^(mpv)$, float"
        "title:^(Authentication Required)$, float"
        "class:^(com.heroicgameslauncher.hgl)$, title:!:(Heroic Games Launcher), float"
        "class:^([Ss]team)$, title:!^([Ss]team)$, float"
        "class:([Tt]hunar), title:!:(.*[Tt]hunar.*), float"
        "initialTitle:(Add Folder to Workspace), float"
        "initialTitle:(Open Files), float"
        "initialTitle:(wants to save), float"
        "class:^([Ww]aypaper)$, float"
        "initialTitle:(Open Files), size 70% 60%"
        "initialTitle:(Add Folder to Workspace), size 70% 60%"
        "tag:settings*, size 70% 70%"
        "class:^([Ff]erdium)$, size 60% 70%"
        "tag:browser*, opacity 1.0 1.0"
        "tag:projects*, opacity 0.9 0.8"
        "tag:im*, opacity 0.94 0.86"
        "tag:file-manager*, opacity 0.9 0.8"
        "tag:terminal*, opacity 0.8 0.7"
        "tag:settings*, opacity 0.8 0.7"
        "class:^(gedit|org.gnome.TextEditor|mousepad)$, opacity 0.8 0.7"
        "class:^(seahorse)$, opacity 0.9 0.8"
        "title:^(Picture-in-Picture)$, opacity 0.95 0.75"
        "title:^(Picture-in-Picture)$, pin"
        "title:^(Picture-in-Picture)$, keepaspectratio"
        "tag:games*, noblur"
        "tag:games*, fullscreen"
      ];
    };

    extraConfig = "
      monitor=,preferred,auto,auto
    ";
  };
}
